### PR TITLE
Fix expired space view

### PR DESCRIPTION
**Pull request by markjs**
When the space is expired the mobile view styling is broken -

win_an_iphone_6s

Furthermore this page could have a little more consideration in terms of design. Open to suggestions.

win_an_iphone_6s

### CODE REVIEW

**Comment by markjs** [comment]
@adambutler 👀 please

**Comment by adambutler** [comment]
Can you add Desktop & Mobile screenshots here please.

**Comment by markjs** [comment]
@adambutler Good shout. Here you go 👍 

screen shot 2016-07-06 at 16 01 28
screen shot 2016-07-06 at 16 01 36

**Comment by adambutler** [comment]
:shipit:

**Pull request merged**
